# This is a basic workflow to help you get started with Actions

name: Label required

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches: [master]
    types: [opened, assigned, synchronize, reopened, labeled, unlabeled]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  label-required:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Get label length
        id: getlength
        env:
          labels: ${{ toJson(github.event.pull_request.labels) }}
        run: |
          echo "$labels"
          LL=$(echo $labels | jq '. | length' )
          echo "::set-output name=Label_length:::$LL"

      - name: Run label checks
        if: ${{ steps.getlength.outputs.Label_length }} == 0
        # if: steps.getlength.outputs.Label_length == 0
        run: |
          core.setFailed('Label required, failing workflow')
